config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  get '/about' => 'site#about'
  get '/contact' => 'site#contact' 
  
  get '/logout' => 'users#logout'
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'
  
  get '/cartdel/:id' => 'cart#delete_cartitem'
   
  get '/profil' => 'users#show'
  get '/order/:total' => 'orders#create'
  

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  

  
  resources :items
  resources :orders
  resources :users

  root 'site#welcome'

end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :orders, dependent: :destroy
  
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
   # @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  # GET /users/1/edit
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update_attributes(user_params)
      # Handle a successful update.
      #flash[:notice] = "successful password changed"
      flash[:success] = "successful password changed"

      #format.html { redirect_to @user, notice: 'password was successfully updated.' }
      render :show
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Handle a successful save.
      redirect_to login_path
    else
      render 'new'
    end
  end
  
  #def showOrders
  #  @user = User.find(params[:id])
  #  @orders = @user.orders.paginate(page: params[:page])
  #end

  def logout
    session[:login] = nil
    session[:cart] = nil
    clear_cart
    session[:user_id] = -1
    @current_user = nil
    #flash[:notice] = "User logged out, cart reset."
    redirect_to :controller => :items
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Your profile</h1>
<br><br>
<p>
  <strong>Name:</strong>
  <%= current_user.name %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= current_user.email %>
</p>

<br>



<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <br>
    <a href="/profil">Back</a>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div>
    <br><br>
    <p>If you are already registered please <%= link_to " Log in ", login_path %></p>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1>User profil</h1>
<br><br>
<p>
  <strong>Name:</strong>
  <%= current_user.name %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= current_user.email %>
</p>

<br>

<p><%= link_to 'Change password', edit_user_path(current_user) %></p>

app/views/users/showOrders.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_order">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.orders.any? %>
      <h3>Orders (<%= @user.orders.count %>)</h3>
      <ol class="orders">
        <%= render @orders %>
      </ol>
      <%= will_paginate @orders %>
    <% end %>
  </div>
</div>