config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  get '/about' => 'site#about'
  get '/contact' => 'site#contact' 
  
  get '/logout' => 'users#logout'
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'
  
  get '/cartdel/:id' => 'cart#delete_cartitem'
   
  get '/profil' => 'users#show'
  get '/order/:total' => 'orders#create'
  

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  

  
  resources :items
  resources :orders
  resources :users

  root 'site#welcome'

end

app/models/item.rb
class Item < ApplicationRecord
mount_uploader :image, ImageUploader 
#validates :content, presence: true, length: { maximum: 140 } 

def self.search(query)
  where("title like ? OR description like ? OR price like ?" , "%#{query}%", "%#{query}%", "%#{query}%") 

end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    if params[:search]
    @items = Item.search(params[:search]).order("created_at ASC")
    else
    @items = Item.all.order('created_at ASC')
    end
  end


  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      
        params.require(:item).permit(:title, :description, :price, :image, :remove_image)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item, html: { multipart: true }) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image_url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %> 
    <% end %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>
<br><br>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Catalog</h1>

<br><br>

<table>

<% @items.each do |item| %>

   <tr >
     <td >
         <div class="image" style="padding-top:20px;padding-bottom=10px;">

         <%= image_tag item.image_url if item.image? %>
         </div>
     </td>

     <td>
         &nbsp;&nbsp;
         <div class="title">
            &nbsp;&nbsp; <%= link_to item.title, item %>
         </div>
         <div class="description">
            &nbsp;&nbsp; <%=h item.description %> &nbsp;&nbsp;
         </div>
         <div class="price">
           &nbsp;&nbsp;  <%= number_to_currency(item.price, :unit =>
'€') %> &nbsp;&nbsp;
         </div>
         <div class="links">
             <br>
             <% if session[:login] == 1 %>
              &nbsp;&nbsp; <%= link_to 'Edit', edit_item_path(item) %> | &nbsp;&nbsp;
             &nbsp;&nbsp;  <%= link_to 'Delete', item, method: 
:delete,   data: { confirm: 'Are you sure?' } %> &nbsp;&nbsp;
             <% else %>
             &nbsp;&nbsp;  <a href="/cart/<%= item.id %>">Add to Cart</a> &nbsp;&nbsp;
             <% end %>
             &nbsp;&nbsp;
             <br><br>
         </div>
     </td>

   </tr>


<% end %>
</table>

<% if session[:login] == 1 %>
     <p><%= link_to 'New item', new_item_path %></p> <% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<br><br>
<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>


<p>
  <strong>Image:</strong>
  
  <%= image_tag @item.image_url if @item.image? %>
</p>
<% if session[:login] != 1 %>
  <%= link_to 'Edit', edit_item_path(@item) %> |
  <%= link_to 'Back', items_path %> |
  <a href="/cart/<%= @item.id %>">Add to Cart</a> 
<% else %>
  <%= link_to 'Edit', edit_item_path(@item) %> |
  <%= link_to 'Back', items_path %>
<% end %>