config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  get '/about' => 'site#about'
  get '/contact' => 'site#contact' 
  
  get '/logout' => 'users#logout'
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'
  
  get '/cartdel/:id' => 'cart#delete_cartitem'
   
  get '/profil' => 'users#show'
  get '/order/:total' => 'orders#create'
  

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  

  
  resources :items
  resources :orders
  resources :users

  root 'site#welcome'

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/about.html.erb
<h1>About the Company</h1>
<br>
<p>GIFT4MM is an international company that is evolving rapidly.</p>
<p>But how did GIFT4MM become what it is today?
<br>On 4 December, 1924, Martien Jonkers was born in Helmond. 
On his 21st birthday Martien started his own business. <br></p>
<p>
With Jonkers’ Handelsonderneming (commercial enterprise) he laid the foundation of GIFT4MM.
He was one of the first people to introduce pens imprinted with advertisements to the Dutch (and European) market. 
<br>His ambitions went beyond the Dutch borders and in 1961 GIFT4MM was founded, 
which is short for International Gift Organisation. GIFT4MM focused on selling promotional gifts to companies, 
foundations, institutions and the government.</p>

app/views/site/contact.html.erb
<h1>Contact</h1>
<p>GIFT4MM Ltd</p>
<p>PO Box 11664
<br>Dublin 2
<br>Ireland</p>

<p>Tel: 0834441555
<br>Fax: 0834441555
<br>Email: info@gift4mm.ie
<br>Online: www.gift4mm.ie
<br>Twitter:@gift4mm
<br>Facebook: GIFT4MM</p>

<p>Registered in the England & Wales 6400537
<br>VAT number  GB 923 2678 19</p>

app/views/site/welcome.html.erb
<h1>Welcome in our gift shop</h1>
<br>
<p>Please <%= link_to 'login',login_path %> or <%= link_to 'sign up',signup_path %></p>