config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  get '/about' => 'site#about'
  get '/contact' => 'site#contact' 
  
  get '/logout' => 'users#logout'
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'
  
  get '/cartdel/:id' => 'cart#delete_cartitem'
   
  get '/profil' => 'users#show'
  get '/order/:total' => 'orders#create'
  

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  

  
  resources :items
  resources :orders
  resources :users

  root 'site#welcome'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gift4mm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="http://code.jquery.com/jquery-1.4.2.min.js"></script>
</head>
<body>
  <div id='header'>
  <!-- Header Image Displayes here -->
  </div>
  <div id='menu'>
    <div id="navbar">
      <ul>
        <li><a href="/items">Products</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact Us</a></li>
        <li><a href="/cart">View Cart</a></li>
        
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              My account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><a href="/profil">Profil</a></li>
              <% if session[:login] != 1 %>
                <li><%= link_to "Orders", orders_path %></li>
              <% end %>
              <li class="divider"></li>
              <li>
                <a href="/logout">Logout</a>
              </li>
            </ul>
          </li>
        <% else %>
          <li><a href="/login">Login</a></li>
        <% end %>
        
        
      </ul>
    </div> 
  </div>
  <div id='container'>
    <div id='content'>
      <div id="user_nav">
        <% if current_user %>
          <% if session[:login] == 1 %>
            Logged in as Admin
          <% else %>
            Logged in as <%= current_user.email %>
          <% end %>
        <% else %>
          Nobody is logged in
        <% end %>
      </div>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
  		<%= yield %>
    </div>
    <div id='first-column'>
    	<div class="searchbox">
    		<h2 class="BoxHeaders">Search</h2>
    		<!--<input type="text" name="search" /><input type="submit" value="Search" />-->
    		<%= form_tag(items_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Items" %>
  <%= submit_tag "Search", :title => nil %> 
  <% end %> 
    	</div>
      <div class="box">
        <h2 class="BoxHeaders">Special Offer</h2>
        <img src="/assets/Books/Pict1.jpg" name="Rotating" id="Rotating1" alt="Special Offers	">
    		<script type="text/javascript">
    			RotateImages(1,0);
    		</script>
    	</div>
    	<div class="box">
    		<h2 class="BoxHeaders">New Product</h2>
    		<img src="/assets/Books/Pict2.jpg" alt="New Products">
    	</div>
    </div>
  </div>
  <div id='footer'>
    <h6 class="footertext">&copy; JACEK BYZDRA  and   NIKOLETT PALYI &trade; 2016</h6>
  </div>
</body>
</html>